<a href="https://colab.research.google.com/github/Vynn0/DAA/blob/main/DAA_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Lists

In [ ]:
aList = ["John", 33, "Toronto", True]
print(aList)

['John', 33, 'Toronto', True]


In [ ]:
from datetime import date # Import date library

date_today = date.today() # 'today" variable to take in the date today
mahasiswa = ["Halvino Iqbal N.", "2022071019", "Informatika", "Desain Analisis Algoritma", str(date_today), "Universitas Pembangunan Jaya."] # Initalize mahasiswa as a list including the date

print(mahasiswa)

['Halvino Iqbal N.', '2022071019', 'Informatika', 'Desain Analisis Algoritma', '2023-09-13', 'Universitas Pembangunan Jaya.']


In [ ]:
bin_colors = ['Red', 'Green', 'Blue', 'Yellow']
print(bin_colors[1])

Green


In [ ]:
from datetime import date # Import date library

date_today = date.today() # 'today" variable to take in the date today
mahasiswa = ["Halvino Iqbal N.", "2022071019", "Informatika", "Desain Analisis Algoritma", str(date_today), "Universitas Pembangunan Jaya."] # Initalize mahasiswa as a list including the date

print("NIM: " + mahasiswa[1]) # Pencetakan / Print NIM
print("Nama Universitas: " + mahasiswa[5]) # Pencetakan / Print nama universitas

NIM: 2022071019
Nama Universitas: Universitas Pembangunan Jaya.


In [ ]:
from datetime import date # Import date library

date_today = date.today() # 'today" variable to take in the date today
mahasiswa = ["Halvino Iqbal N.", "2022071019", "Informatika", "Desain Analisis Algoritma", str(date_today), "Universitas Pembangunan Jaya."] # Initalize mahasiswa as a list including the date
mhswLen = len(mahasiswa)

for x in range(mhswLen):
  print(mahasiswa[x], x)
else:
  print(mahasiswa)

Halvino Iqbal N. 0
2022071019 1
Informatika 2
Desain Analisis Algoritma 3
2023-09-13 4
Universitas Pembangunan Jaya. 5
['Halvino Iqbal N.', '2022071019', 'Informatika', 'Desain Analisis Algoritma', '2023-09-13', 'Universitas Pembangunan Jaya.']


In [ ]:
bin_colors = ['Red', 'Green', 'Blue', 'Yellow']
print(bin_colors[3:4]) # [Index from 0]

In [ ]:
bin_colors=['Red', 'Green', 'Blue', 'Yellow']
for aColor in bin_colors:
  print(aColor + " Square")


In [ ]:
from datetime import date # Import date library

date_today = date.today() # 'today" variable to take in the date today
mahasiswa = ["Halvino Iqbal Nataprawira", "2022071019", "Informatika", "Desain Analisis Algoritma", str(date_today), "Universitas Pembangunan Jaya"] # Initalize mahasiswa as a list including the date

for mhsw in mahasiswa:
  print("UPJ " + mhsw)

UPJ Halvino Iqbal Nataprawira
UPJ 2022071019
UPJ Informatika
UPJ Desain Analisis Algoritma
UPJ 2023-09-13
UPJ Universitas Pembangunan Jaya


## Tuples

In [ ]:
bin_colors = ('Red', 'Green', 'Blue', 'Yellow')
print(bin_colors[1])
print(bin_colors[2:])

Green
('Blue', 'Yellow')


In [ ]:
UPJ = ('Universitas', 'Pembangunan', 'Jaya')
print(UPJ)

('Universitas', 'Pembangunan', 'Jaya')


In [ ]:
pertama = (100)
kedua = (200, 400, 600)
ketiga = (300)
keempat = (400, 800)

nested_tuple = (pertama, kedua, ketiga, keempat)
print(nested_tuple)

(100, (200, 400, 600), 300, (400, 800))


## Dictionary

In [ ]:
bin_colors = {
    "manual_color": "Yellow",
    "approved_color": "Green",
    "refused_Color": "Red"
}
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_Color': 'Red'}


In [ ]:
bin_colors = {
    "manual_color": "Yellow",
    "approved_color": "Green",
    "refused_Color": "Red"
}

appr = bin_colors.get("approved_color") # To get the desired key
print(appr)

Green


In [ ]:
bin_colors = {
    "manual_color": "Yellow",
    "approved_color": "Green",
    "refused_Color": "Red"
}

bin_colors['approved_color']="Purple" # To change the desired key value
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Purple', 'refused_Color': 'Red'}


In [ ]:
mahasiswa = {
    "Nama": "Halvino Iqbal Nataprawira",
    "NIM": "20220710191",
    "Prodi": "Informatika",
    "Universitas": "UPJ"
}

print(mahasiswa)

{'Nama': 'Halvino Iqbal Nataprawira', 'NIM': '20220710191', 'Prodi': 'Informatika', 'Universitas': 'UPJ'}


## Sets

In [ ]:
green = {'grass', 'leaves'}
print(green)

In [ ]:
set_01 = {4,5,6,2}
print(set_01)

set_02 = set()
set_03 = set([2,1,4,3]) # Becomes set
print(type(set_02))
print(set_03)

In [ ]:
set_01 = {4,5,6,2}
print(set_01[1]) # Akan error

In [ ]:
set_04 = {2,3,4,5,6}
set_04.add(1)
print(set_04)

{1, 2, 3, 4, 5, 6}


In [ ]:
set_04 = {1,2,3,4,5,6,7,8}
set_04.discard(4) # Erases value 4
print(set_04)

set_04.add(10) # Add a value of 10
print(set_04)

{1, 2, 3, 5, 6, 7, 8}
{1, 2, 3, 5, 6, 7, 8, 10}


In [ ]:
set_A = {1,2,3,4} # Union
set_B = {3,4,5,6}
print(set_A|set_B)
print(set_A.union(set_B))

{1, 2, 3, 4, 5, 6}
{1, 2, 3, 4, 5, 6}


In [ ]:
set_A = {1,2,3,4} # Intersection
set_B = {3,4,5,6}
print(set_A & set_B)
print(set_A.intersection(set_B))

{3, 4}
{3, 4}


In [ ]:
set_A = {1,2,3,4} # Difference (What it have the other don't)
set_B = {3,4,5,6}
print(set_A - set_B) # A - B
print(set_A.difference(set_B))

print(set_B - set_A) # B - A
print(set_B.difference(set_A))

In [ ]:
set_A = {1,2,3,4} # Symmetric Difference (What both have the other don't)
set_B = {3,4,5,6}

print(set_A ^ set_B) # A - B
print(set_A.symmetric_difference(set_B))

{1, 2, 5, 6}
{1, 2, 5, 6}


In [ ]:
yellow = {"dandelions", "leaves", "fire hydrant"} # Latihan
red = {"rose", "blood", "leaves", "fire hydrant"}

print(yellow|red)
print(yellow&red)

{'dandelions', 'blood', 'leaves', 'rose', 'fire hydrant'}
{'leaves', 'fire hydrant'}


## DataFrames

In [ ]:
import pandas as pd

df = pd.DataFrame([
    ['1', 'Fares', 32, True],
    ['2', 'Elena', 23, True],
    ['3', 'Steven', 40, True]
])

df.columns = ['id', 'name', 'age', 'decision']

print(df)

  id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23      True
2  3  Steven   40      True


In [ ]:
print(df[['name', 'age']]) # Seleksi Kolom / Column Selection

print(df.iloc[:,3])

     name  age
0   Fares   32
1   Elena   23
2  Steven   40
0    True
1    True
2    True
Name: decision, dtype: bool


In [ ]:
print(df.iloc[1:3,:]) # Seleksi Row / Row solection

print(df[df.age>30])

print(df[(df.age<35)&(df.decision==True)])

  id    name  age  decision
1  2   Elena   23      True
2  3  Steven   40      True
  id    name  age  decision
0  1   Fares   32      True
2  3  Steven   40      True
  id   name  age  decision
0  1  Fares   32      True
1  2  Elena   23      True


In [ ]:
data = {'satu': [1,1,1,1,1],
        'dua': [2,2,2,2,2],
        'tiga': [3,3,3,3,3]}

df = pd.DataFrame(data, index=['a','b','c','d','e']) # mengganti index menjadi abcde
df.head()

satu  dua  tiga
a     1    2     3
b     1    2     3
c     1    2     3
d     1    2     3
e     1    2     3

In [ ]:
import numpy as np

myMatrix = np.array([[11,12,13], [21,22,23], [31,32,33]])
print(myMatrix)

print(type(myMatrix)) # Untuk mengetahui tipe data / To find the data type

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [ ]:
matriksC = np.array([[1,2,3], [4,5,6]])
print("Matriks C: \n", matriksC)

transpose_matriks = np.transpose(matriksC)

print("Transpose Matriks C: \n", transpose_matriks)

Matriks C: 
 [[1 2 3]
 [4 5 6]]
Transpose Matriks C: 
 [[1 4]
 [2 5]
 [3 6]]


In [ ]:
matrix = np.array([[100,200,300], [700,600,500], [900,100,800]]) # Welcome to the matrix
transpose = np.transpose(matrix)

print(matrix)
print("\n")
print(transpose)

[[100 200 300]
 [700 600 500]
 [900 100 800]]


[[100 700 900]
 [200 600 100]
 [300 500 800]]


## Vector

In [ ]:
myVector = [22,33,44,55]
print(myVector)
print(type(myVector))

In [ ]:
import numpy as np
myVector = np.array([22,33,44,55]) # Using numpy
print(myVector)
print(type(myVector))

[22 33 44 55]
<class 'numpy.ndarray'>


## Stack

In [ ]:
class Stack:
  def __init__(self): # Constructor
    self.items = []
  def isEmpty(self):
    return self.items == [] # Jika/if empty, return self.items
  def push(self, item):
    self.items.append(item)
  def pop(self):
    return self.items.pop()
  def peek(self):
    return self.items[len(self.items)-1]
  def size(self):
    return len(self.items)

stack = Stack()
stack.push('Red')
stack.push('Green')
stack.push('Blue')
stack.push('Yellow')

stack.pop()

'Yellow'

## Queue

In [ ]:
class Queue(object):
  def __init__(self):
    self.items = []
  def isEmpty(self):
    return self.items == []
  def enqueue(self, item):
    self.items.insert(0,item)
  def dequeue(self):
    return self.items.pop()
  def size(self):
    return len(self.items)

queue = Queue()
queue.enqueue('Red')
queue.enqueue('Green')
queue.enqueue('Blue')
queue.enqueue('Yellow')

print(queue.size())

print(queue.dequeue())

print(queue.dequeue())

## Tree

In [ ]:
class Node:
  def __init__(self, data):
    self.left = None
    self.right = None
    self.data = data
  def PrintTree(self):
    if self.left:
      self.left.PrintTree()
    print(self.data),
    if self.right:
      self.right.PrintTree()

root = Node(2)
root.left = Node(3)
root.right = Node(5)
root.left.left = Node(7)
root.left.right = Node(9)
root.right.left = Node(11)
root.right.right = Node(13)
root.PrintTree()

7
3
9
2
11
5
13
